version: "3"
services:
  app:
    container_name: ticket-service
    restart: always
    build: ./
    ports:
      - "3000:${PORT}"
    volumes: 
      - ".:/app"
    depends_on: 
      - mongo
    
  mongo:
    container_name: mongo-ticket-service
    image: mongo
    ports:
      - "${MONGO_PORT}:27017"